### ISSUE TITLE
Fatal Error when trying to activate...

### ISSUE THREAD

**Issue by camosoul** [nomiddleman/nomiddleman-woocommerce#31]
Click "activate" link, this happens:
```
Plugin could not be activated because it triggered a fatal error.

Fatal error: Array and string offset access syntax with curly braces is no longer supported in /usr/share/nginx/html/store/wp-content/plugins/nomiddleman-crypto-payments-for-woocommerce/src/NMM_Util.php on line 54

Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/log-handlers/class-wc-log-handler-file.php:149 Stack trace: #0 /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/log-handlers/class-wc-log-handler-file.php(149): fclose() #1 /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/log-handlers/class-wc-log-handler-file.php(209): WC_Log_Handler_File->open() #2 /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/log-handlers/class-wc-log-handler-file.php(101): WC_Log_Handler_File->add() #3 /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/class-wc-logger.php(146): WC_Log_Handler_File->handle() #4 /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/class-wc-logger.php(192): WC_Logger->log() #5 /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/class-woocommerce.php(225): WC_Logger->critical() #6 [internal function]: WooCommerce->log_errors() #7 {main} thrown in /usr/share/nginx/html/store/wp-content/plugins/woocommerce/includes/log-handlers/class-wc-log-handler-file.php on line 149
```
Might be an easy fix?
`Array and string offset access syntax with curly braces is no longer supported`
PHP 8.0.3
WP 5.7
WC 5.1
Arch Linux

**Comment by alexv66** [comment]
@rgostic do you still support this plugin ?
as I see, you pushed last updates to
https://plugins.trac.wordpress.org/log/nomiddleman-crypto-payments-for-woocommerce/?limit=100&mode=stop_on_copy&format=rss

we can continue work over this plugin if you transfer ownership

**Comment by tlaurion** [comment]
Will switch to https://coinmarketstats.online/product/woocommerce-bitcoin-altcoin-payment-gateway?utm_source=wordpress.org&utm_medium=README&utm_campaign=woo-altcoin-payment-gateway

This project is dead unfortunately.

**Comment by alexv66** [comment]
@tlaurion we have a client who want to revive the project and going to pay for the work.

So we seek for way to take ownership of https://wordpress.org/plugins/nomiddleman-crypto-payments-for-woocommerce/
is it possible @rgostic  ? @nomiddleman ?
